### ISSUE TITLE
Did this plugin ever worked?

### ISSUE THREAD

**Issue by cristianbregant** [anarchuser/speech#1]
Using this plugin both 0.0.1 and 0.0.2 crashes on:
```
java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-310
E/AndroidRuntime( 6043):        at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:807)
E/AndroidRuntime( 6043):        at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:697)
E/AndroidRuntime( 6043):        at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:80)
E/AndroidRuntime( 6043):        at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:172)
E/AndroidRuntime( 6043):        at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:117)
E/AndroidRuntime( 6043):        at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.success(EventChannel.java:226)
E/AndroidRuntime( 6043):        at com.code.aaron.speech.SpeechPlugin$1.run(SpeechPlugin.java:58)
E/AndroidRuntime( 6043):        at java.lang.Thread.run(Thread.java:818)
```

Will this plugin ever work in the future or is it dead?

**Comment by anarchuser** [comment]
No and very good question

**Comment by anarchuser** [comment]
I haven't been able to call the Google Speech API from it, and don't have time to work on it.
Sorry for not making that clear in the README.


To your original issue, the bug is caused by the newest version of Flutter, but fixing that still wouldn't make the plugin run
